import { chromium } from '@playwright/test';
import assert from 'node:assert/strict';
const browser = await chromium.launch({ executablePath: process.env.PIXELFRAME_CHROME || '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome', headless: true });
try {
  const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
  const errors = []; page.on('pageerror', error => errors.push(error.message));
  await page.goto(process.env.PIXELFRAME_URL || 'http://localhost:5173');
  const inspector = page.getByRole('separator', { name: 'Redimensionar panel de extracción' });
  const tray = page.getByRole('separator', { name: 'Redimensionar bandeja de capturas' });
  let initial = await inspector.boundingBox();
  await page.mouse.move(initial.x + initial.width / 2, initial.y + 100); await page.mouse.down();
  await page.mouse.move(initial.x - 90, initial.y + 100, { steps: 12 }); await page.mouse.up();
  assert.ok(Number(await inspector.getAttribute('aria-valuenow')) > 375);
  initial = await tray.boundingBox();
  await page.mouse.move(500, initial.y + initial.height / 2); await page.mouse.down();
  await page.mouse.move(500, initial.y - 95, { steps: 12 }); await page.mouse.up();
  assert.ok(Number(await tray.getAttribute('aria-valuenow')) > 255);
  await inspector.focus(); await page.keyboard.press('ArrowRight');
  const width = Number(await inspector.getAttribute('aria-valuenow'));
  assert.ok(width > 365 && width < 390);
  await page.getByRole('button', { name: 'Ocultar panel de extracción', exact: true }).click();
  await page.waitForTimeout(350);
  assert.equal(await page.locator('#extraction-panel').getAttribute('aria-hidden'), 'true');
  assert.ok((await page.locator('#extraction-panel').boundingBox()).width < 1);
  await page.getByRole('button', { name: 'Ocultar bandeja de capturas', exact: true }).click();
  await page.waitForTimeout(350);
  assert.equal(await page.locator('#capture-tray').getAttribute('aria-hidden'), 'true');
  assert.ok((await page.locator('#capture-tray').boundingBox()).height < 1);
  await page.reload();
  assert.equal(await page.locator('#extraction-panel').getAttribute('aria-hidden'), 'true');
  await page.getByRole('button', { name: 'Mostrar panel de extracción', exact: true }).click();
  await page.getByRole('button', { name: 'Mostrar bandeja de capturas', exact: true }).click();
  await page.waitForTimeout(350);
  assert.equal(Number(await inspector.getAttribute('aria-valuenow')), width);
  assert.ok(Number(await tray.getAttribute('aria-valuenow')) > 255);
  await page.screenshot({ path: '/private/tmp/pixelframe-panels.png', fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 });
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
  await page.getByRole('button', { name: 'Ocultar panel de extracción', exact: true }).click();
  await page.waitForTimeout(350);
  assert.ok((await page.locator('#extraction-panel').boundingBox()).height < 1);
  assert.deepEqual(errors, []);
  console.log('PASS: mouse/keyboard resize, smooth hiding, full-width viewer, restore saved sizes, reload persistence, mobile visibility.');
} finally { await browser.close(); }
